### ISSUE TITLE
Support for ember 2.x?

### ISSUE THREAD

**Issue by peterjmag** [alexlafroscia/ember-cli-react#6]
Hi! Does this addon support Ember 2.x? I'm working with an Ember app that's running 2.14.2, and I'm getting the following after installation:

```
$ ember server
[...]
The Broccoli Plugin: [BroccoliMergeTrees: TreeMerger (vendor & appJS)] failed with:
Error: ENOENT: no such file or directory, open '/Users/peterjmag/git/[project-name]/tmp/source_map_concat-input_base_path-1IIoQwbO.tmp/node_modules/react/umd/react.development.js'
```

`package.json` makes me think that it only supports 3.x, but I thought I'd check first before I go through the whole process of upgrading my Ember app! And if not, perhaps I can do some digging and see if I can help contribute compatibility for 2.x. ☺️

**Comment by alexlafroscia** [comment]
Alright, a few things to work through first:

What is your `ember-cli` version? [Directly importing from `node_modules` is only supported in version 2.15+ of the CLI](https://emberjs.com/blog/2017/09/01/ember-2-15-released.html#toc_app-import-files-within-node_modules); if you're running Ember 2.14, I would recon there's a good chance you're on Ember CLI 2.14 as well. You should be able to bump to Ember CLI 2.15 without breaking your application, and compatibility with this addon should be improved.

If you're using Ember CLI 2.15+ already, can you try go into your `node_modules` directory and make sure that there is a `react` and `react-dom` directory in there, and those directories have the expected files in the `umd` directory? The relevant import code in the addon can be found [here](https://github.com/alexlafroscia/ember-cli-react/blob/376e9016a539833dfcc843657c6bd10337837f19/index.js#L21-L39) as a reference for what files are imported.

If neither of those is the issue, React must have changed their folder structure and the files no longer exist in those locations. In that case, I have a bug to fix!

**Comment by alexlafroscia** [comment]
Cool, it's just the `ember-cli` version that's the issue.

If you want to refactor to use something like [`ember-cli-node-assets`](https://github.com/dfreeman/ember-cli-node-assets) instead of directly importing from `node_modules` that's OK with me, but it wasn't worth it for me to do that work up-front for an experiment like this. 

Personally, I think that a README warning and setting a `peerDependency` of `ember-cli >= 2.15.0` is good enough. If you do make the PR for the README and can add that `peerDependency`, that would be super!

**Comment by peterjmag** [comment]
Yep, that makes sense to me. I'll open a PR when I'm back on my work machine tomorrow!
